spring:
  application:
    name: app
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: hello-service
          uri: lb://HELLO-SERVICE
          predicates:
            - Path=/api/hello
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 100
                  burstCapacity: 100
#  redis:
#    host: localhost
#    port: 6379

server:
  port: 8080

resilience4j:
  ratelimiter:
    instances:
      helloLimiter:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 0
