spring:
  application:
    name: app
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedMethods: "*"
            allowedHeaders: "*"
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
