apiVersion: v1
kind: Service
metadata:
  name: CloudNativeFinal-service
spec:
  selector:
    app: CloudNativeFinal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer